# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ServerlessButton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ServerlessButton
   pod 'OpenWhisk', :git => 'https://github.com/apache/incubator-openwhisk-client-swift.git', :tag => '0.3.0'
   pod 'SwiftyJSON', '~> 4.0'

  target 'ServerlessButtonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ServerlessButtonUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end

